name: Pytest UNIT

on:
 pull_request:
   branches:
     - "**"
jobs:
 build:
   runs-on: ubuntu-latest
   steps: 
    - uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install debs 
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry install
    - name: Start tests
      run: echo test
